# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  arm1_to_arm2:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  base_link_to_tower:
    has_velocity_limits: true
    max_velocity: 0.75
    has_acceleration_limits: false
    max_acceleration: 0
  tower_to_arm1:
    has_velocity_limits: true
    max_velocity: 0.006
    has_acceleration_limits: false
    max_acceleration: 0