
# Simulation settings for using moveit_sim_controllers
#moveit_sim_hw_interface:
#  joint_model_group: Scara_Arm
#  joint_model_group_pose: T Pose
# Settings for ros_control_boilerplate control loop
#generic_hw_control_loop:
#  loop_hz: 300
#  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - base_link_to_tower
    - tower_to_arm1
    - arm1_to_arm2
  sim_control_mode: 0  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - base_link_to_tower
      - tower_to_arm1
      - arm1_to_arm2


#THIS IS FOR ROS_CONTROL


arm_controller:
  type: position_controllers/JointTrajectoryController #position_controllers/JointGroupPositionController #effort_controllers/JointPositionController # #position_controllers
  joints:
    - base_link_to_tower
    - tower_to_arm1
    - arm1_to_arm2
  constraints:
    stopped_velocity_tolerance: 0.02

    base_link_to_tower:
      goal: 0.03
    tower_to_arm1:
      goal: 0.01
    arm1_to_arm2:
      goal: 0.05

  #gains:
  #  base_link_to_tower:
  #    p: 100
  #    d: 1
  #    i: 1
  #    i_clamp: 1
  #  tower_to_arm1:
  #    p: 100
  #    d: 1
  #    i: 1
  #    i_clamp: 1
  #  arm1_to_arm2:
  #    p: 100
  #    d: 1
  #    i: 1
  #    i_clamp: 1