# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: Scara Arm
  joint_model_group_pose: T Pose
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - base_link_to_tower
    - tower_to_arm1
    - arm1_to_arm2
    - kinect_rotator_to_kinect_pivot
    - kinect_pivot_to_camera_depth_frame
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
controller:
  type: position_controllers/JointPositionController
  joints:
    - base_link_to_tower
    - tower_to_arm1
    - arm1_to_arm2
  gains:
    base_link_to_tower:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    tower_to_arm1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm1_to_arm2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1